### ISSUE TITLE
Erro no fim do programa

### ISSUE THREAD

**Issue by alnuno** [Muttsuri/NetScout#3]
Olá João.
Sempre que corro o programa ocorre o seguinte erro:
C:
Espaço Total em Disco C: : 365 GB
Espaço Ocupado em Disco C: : 80 GB
Espaço Livre em Disco C: : 285 GB
Recovered Space 0 GB
D:
Espaço Total em Disco D: : 547 GB
Espaço Ocupado em Disco D: : 234 GB
Espaço Livre em Disco D: : 313 GB
Recovered Space 0 GB
Contact : The term 'Contact' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Windows\System32\NetScout.ps1:131 char:1
+ Contact GitHub API Training Shop Blog About
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Contact:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

© : The term '©' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Windows\System32\NetScout.ps1:132 char:1
+ © 2017 GitHub, Inc. Terms Privacy Security Status Help
+ ~
    + CategoryInfo          : ObjectNotFound: (©:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Podes ver o que se passa?

Obrigado NA.

**Comment by Muttsuri** [comment]
Foi um erro meu a copiar do GitHub, não um erro do script em si.
Ao copiar ficaram essas duas linhas.
